### ISSUE TITLE
Do not rely on external resources

### ISSUE THREAD

**Issue by astoeckel** [psipeter/investment-game-webapp#9]
Do not download external scripts or fonts. These resources should be directly served from the web server. Doing this increases the reliability of the web service and enables switching to strict content policies (Content Security Policies, CSP), which in turn prevent XSS attacks.

In particular, this includes JQuery, JQuery UI and fonts downloaded from Google Fonts.

**Comment by psipeter** [comment]
Serving fonts locally with 48b443d14986d4bf6f09f94580f96f151137e12f

**Comment by psipeter** [comment]
Serve JQuery and remove JQuery UI with 1f2a0c5d62a41376265d75af09023c03f90fd0e9
